/**
 * Copyright 2015 JiKai. All rights reserved.
 * Use of this source code is governed by a BSD-style
 * license that can be found in the LICENSE file.
 *
 *     This file defines some common typedefs, offers
 * the uniform error handling and memory operations.
 **/

#ifndef CPLUS_COMMON_H
#define CPLUS_COMMON_H

#include <stdio.h>
#include <assert.h>
#include <malloc.h>

#define true   1
#define false -1
typedef char                   bool;
typedef char                   byte;
typedef char                   int8;
typedef short int              int16;
typedef long int               int32;
typedef long long int          int64;
typedef unsigned char          uint8;
typedef unsigned short int     uint16;
typedef unsigned long int      uint32;
typedef unsigned long long int uint64;
typedef float                  float32;
typedef double                 float64;
typedef unsigned char          uchar;

// all error in this compiler program will be generated by
// new_error(char* errmsg).
//
// when you define a function witch may generate some error,
// you should write the definition like below:
//     error foo(bool flag) {...}
//
// when you call the function and want to check the error,
// you can judge like this:
// return value ->     NULL means none error occurs
//                 not NULL means some error occurs
typedef char* error;
extern error new_error(char* errmsg);

// all operations about memory allocating/releasing must use
// the function mem_alloc and mem_free. mem_alloc can process
// the error automatically. mem_free will work well even
// though you free the same memory many times.
extern void* mem_alloc(size_t size);
extern void  mem_free (void *ptr);

// show some message to debug.
extern void  debug(char* msg);

#endif
